name: herb_com
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/logo-removebg-preview (1).png
   - assets/images/logoo000-removebg-preview.png
   - assets/images/wwwwww-removebg-preview.png
   - assets/images/plshjhfhr.jpg
   - assets/images/plnnnnn-removebg-preview.png
   - assets/images/plantimage.jpeg
   - assets/images/plntcare.jpeg
   - assets/images/tips.jpeg
   - assets/images/grdng.jpeg
fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/static/Montserrat-Regular.ttf
    - family: OpenSans  
      fonts:
        - asset : assets/fonts/OpenSans-LightItalic.ttf

  
